language: emacs-lisp
before_install:
#   - sudo apt-get install gcc automake texinfo libmagick++-dev libgtk2.0-dev libxft-dev libgnutls-dev libdbus-1-dev libgif-dev libxpm-dev
#   - sudo mkdir -p /usr/local/evm
#   - sudo chown travis:travis /usr/local/evm
#   - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
#   - export PATH="/home/travis/.cask/bin:$PATH"
#   - export PATH="/home/travis/.evm/bin:$PATH"
#   - if [ -n "$EVM_EMACS" ]; then evm install --skip $EVM_EMACS && evm use $EVM_EMACS ; fi
#   - if [ "$EMACS" = "emacs24" ]; then sudo add-apt-repository -y ppa:cassou/emacs && sudo apt-get update -qq && sudo apt-get install -qq emacs24 emacs24-el; fi
#   - if [ "$EMACS" = "emacs-snapshot" ]; then sudo add-apt-repository -y ppa:ubuntu-elisp/ppa && sudo apt-get update -qq && sudo apt-get install -qq emacs-snapshot emacs-snapshot-el; fi
# rvm:
#   - 1.9.3
# env:
#     - EVM_EMACS=emacs-24.3-bin
#     - EVM_EMACS=emacs-24.4-bin
#     # - EVM_EMACS=emacs-git-snapshot
#     - EMACS=emacs24
#     - EMACS=emacs-snapshot
before_install:
  # Stable Emacs 24.3
  - sudo add-apt-repository -y ppa:cassou/emacs
  # Nightly Emacs snapshot builds
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox
  # Install and bootstrap cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
    - make test
